### ISSUE TITLE
libc crashes after quering an entity

### ISSUE THREAD

**Issue by mrQoldy** [atelier-saulx/based-universal#8]
client crashes after quering the entity

this crash happens only with one request

[Crash query.txt](https://github.com/atelier-saulx/based-universal/files/12486029/Crash.query.txt)

**Comment by mrQoldy** [comment]
query-executedChecklist  {"id":"ecbf9830e0"}

**Comment by frammaa** [comment]
Investigating, might have to switch to c++11 (from c++ 17) which will require some rewriting

**Comment by frammaa** [comment]
This is resolved, issue was that we were not properly handling the case where the discovery did not return a valid URL
